export const languageData=[
    { "label": "English", "value": "en" },
    { "label": "English US", "value": "en_US" },
    { "label": "Hindi", "value": "hi" },
    { "label": "Spanish", "value": "es" },
    { "label": "French", "value": "fr" },
    { "label": "German", "value": "de" },
    { "label": "Arabic", "value": "ar" },
    { "label": "Chinese (Simplified)", "value": "zh-CN" },
    { "label": "Chinese (Traditional)", "value": "zh-TW" },
    { "label": "Japanese", "value": "ja" },
    { "label": "Korean", "value": "ko" },
    { "label": "Portuguese", "value": "pt" },
    { "label": "Russian", "value": "ru" },
    { "label": "Bengali", "value": "bn" },
    { "label": "Tamil", "value": "ta" },
    { "label": "Telugu", "value": "te" },
    { "label": "Malayalam", "value": "ml" },
    { "label": "Marathi", "value": "mr" },
    { "label": "Gujarati", "value": "gu" },
    { "label": "Urdu", "value": "ur" },
    { "label": "Punjabi", "value": "pa" },
    { "label": "Indonesian", "value": "id" },
    { "label": "Turkish", "value": "tr" },
    { "label": "Italian", "value": "it" },
    { "label": "Dutch", "value": "nl" },
    { "label": "Vietnamese", "value": "vi" },
    { "label": "Thai", "value": "th" },
    { "label": "Polish", "value": "pl" }
  ]
  